theme = "m10c"

baseURL = "http://example.com/"
languageCode = "en-us"
title = "Brandon Kurtz"
author = "Brandon Kurtz"
googleAnalytics = ""

[markup.goldmark.renderer]
    unsafe = true

[params]
    description = "I do MacOps & WinOps @ Airbnb. I like golang, config management, and open-source management tools. Views are my own."

[[menu.main]]
    url = "/"
    name = "Blog"
    weight = 1

[[params.social]]
    icon = "github"
    url = "https://github.com/discentem/"
[[params.social]]
    url = "https://macadmins.slack.com/messages/D1PJBJWLT"
    icon = "slack"
[[params.social]]
    url = "https://twitter.com/muffins222221"
    icon = "twitter"
[[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/brandon-kurtz/"
[[params.social]]
    icon = "mail"
    url = "mailto:kurtz.brandon@gmail.com"
